language: python
stages:
  - test
jobs:
  include:
    - stage: test
      python: 3.8
      install:
        - pip install -r test/requirements.txt
        - pip install -r src/layers/api/requirements.txt
        - pip install coveralls
      script:
        - make test
      after_success:
        - coveralls