---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime
  labels:
    app: anime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anime
  template:
    metadata:
      labels:
        app: anime
    spec:
      containers:
        - name: anime
          image: projectmovio/anime-service:0.0.3
          ports:
            - containerPort: 8085
          resources:
            requests:
              memory: "20Mi"
              cpu: "2m"
            limits:
              memory: "40Mi"
              cpu: "100m"
          env:
            - name: ANIME_SERVICE_CLIENT_NAME
              value: "${ANIME_SERVICE_CLIENT_NAME}"
            - name: ANIME_SERVICE_CLIENT_VERSION
              value: "1"
            - name: ANIME_SERVICE_CLIENT_PROTOCOL_VERSION
              value: "1"
            - name: ANIME_SERVICE_CACHE_DIR
              value: "/var/cache/anime_service/"
          volumeMounts:
            - mountPath: "/var/cache/anime_service/"
              name: cache
        - name: titles-updater
          image: projectmovio/anime-titles-updater:0.0.3
          resources:
            requests:
              memory: "5Mi"
              cpu: "2m"
            limits:
              memory: "10Mi"
              cpu: "20m"
          env:
            - name: ANIME_SERVICE_CACHE_DIR
              value: "/var/cache/anime_service/"
          volumeMounts:
            - mountPath: "/var/cache/anime_service/"
              name: cache
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: anime