name: deploy

on:
  push:
    branches: [ master, github-cdk-action ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: 'projectmovio/anime-service'

      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v1.1.10
        with:
          cdk_stack: anime
          cdk_version: 1.49.1
          cdk_subcommand: diff
          debug_log: true
          working_dir: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MAL_CLIENT_ID: ${{ secrets.MAL_CLIENT_ID }}
          ANIDB_CLIENT: ${{ secrets.ANIDB_CLIENT }}
          AWS_DEFAULT_REGION: eu-west-1

      - name: cdk synth
        uses: youyo/aws-cdk-github-actions@v1.1.10
        with:
          cdk_stack: anime
          cdk_version: 1.49.1
          cdk_subcommand: synth
          debug_log: true
          working_dir: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MAL_CLIENT_ID: ${{ secrets.MAL_CLIENT_ID }}
          ANIDB_CLIENT: ${{ secrets.ANIDB_CLIENT }}
          AWS_DEFAULT_REGION: eu-west-1